In [27]:
import pandas as pd

In [28]:
matches = pd.read_csv("matches.csv")

In [29]:
matches.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,PK,PKatt,xG.1,npxG,npxG/Sh,G-xG,np:G-xG,Match Report.1,Team,ï»¿Date
0,06/08/2023,16:00,Community Shield,FA Community Shield,Sun,Neutral,D,1 (1),1 (4),Arsenal,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Match Report,Manchester_City,NaN
1,11/08/2023,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0.0,0.0,1.9,1.9,0.12,1.1,1.1,Match Report,Manchester_City,NaN
2,16/08/2023,22:00 (20:00),Super Cup,UEFA Super Cup,Wed,Home,D,1 (5),1 (4),es Sevilla,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Match Report,Manchester_City,NaN
3,19/08/2023,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0.0,0.0,1.0,1.0,0.07,0.0,0.0,Match Report,Manchester_City,NaN
4,27/08/2023,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,0.0,1.0,3.5,2.8,0.10,-1.5,-0.8,Match Report,Manchester_City,NaN

In [30]:
matches_columns = matches.columns
print(matches_columns)

Index(['Date', 'Time', 'Comp', 'Round', 'Day', 'Venue', 'Result', 'GF', 'GA',
       'Opponent', 'xG', 'xGA', 'Poss', 'Attendance', 'Captain', 'Formation',
       'Opp Formation', 'Referee', 'Match Report', 'Notes', 'Date.1', 'Time.1',
       'Comp.1', 'Round.1', 'Day.1', 'Venue.1', 'Result.1', 'GF.1', 'GA.1',
       'Opponent.1', 'Gls', 'Sh', 'SoT', 'SoT%', 'G/Sh', 'G/SoT', 'Dist', 'FK',
       'PK', 'PKatt', 'xG.1', 'npxG', 'npxG/Sh', 'G-xG', 'np:G-xG',
       'Match Report.1', 'Team', 'ï»¿Date'],
      dtype='object')

In [31]:
matches.drop(columns='ï»¿Date')

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,xG.1,npxG,npxG/Sh,G-xG,np:G-xG,Match Report.1,Team
0,06/08/2023,16:00,Community Shield,FA Community Shield,Sun,Neutral,D,1 (1),1 (4),Arsenal,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Match Report,Manchester_City
1,11/08/2023,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0.0,0.0,0.0,1.9,1.9,0.12,1.1,1.1,Match Report,Manchester_City
2,16/08/2023,22:00 (20:00),Super Cup,UEFA Super Cup,Wed,Home,D,1 (5),1 (4),es Sevilla,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Match Report,Manchester_City
3,19/08/2023,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0.0,0.0,0.0,1.0,1.0,0.07,0.0,0.0,Match Report,Manchester_City
4,27/08/2023,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,2.0,0.0,1.0,3.5,2.8,0.10,-1.5,-0.8,Match Report,Manchester_City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1966,5/3/2025,15:00,Premier League,Matchweek 35,Sat,Away,L,0,2,Leicester City,...,0.0,0.0,0.0,0.5,0.5,0.07,-0.5,-0.5,Match Report,Southampton
1967,5/10/2025,15:00,Premier League,Matchweek 36,Sat,Home,D,0,0,Manchester City,...,0.0,0.0,0.0,0.1,0.1,0.05,-0.1,-0.1,Match Report,Southampton
1968,5/18/2025,12:00,Premier League,Matchweek 37,Sun,Away,L,0,2,Everton,...,0.0,0.0,0.0,1.2,1.2,0.22,-1.2,-1.2,Match Report,Southampton
1969,5/25/2025,16:00,Premier League,Matchweek 38,Sun,Home,L,1,2,Arsenal,...,1.0,0.0,0.0,0.6,0.6,0.09,0.4,0.4,Match Report,Southampton
1970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,1.0,3.0,NaN,NaN,0.09,38.0,37.0,NaN,Southampton

In [32]:
matches['Team'].value_counts()

Team
Manchester_City            116
Liverpool                  116
Aston_Villa                115
Manchester_United          114
Arsenal                    112
Chelsea                    110
Tottenham_Hotspur          103
Brighton_&_Hove_Albion      97
West_Ham_United             96
Crystal_Palace              92
Fulham                      92
Wolverhampton_Wanderers     90
Nottingham_Forest           90
Everton                     89
Bournemouth                 89
Brentford                   87
Newcastle                   52
Newcastle_United            49
Southampton                 45
Luton_Town                  45
Leicester_City              44
Burnley                     43
Ipswich_Town                43
Sheffield_United            42
Name: count, dtype: int64